TAWS-8 Rename pre-receive.

diff --git a/.husky/pre-receive b/.husky/pre-receive
--- a/.husky/pre-receive
+++ b/.husky/pre-receive
@@ -77,3 +77,17 @@ echo "Version bumped to $new_version"
 echo "Keep package-lock.json up to spec"
 npm install
 git commit -m "[Husky Hook] AutoBump Version" package.json package-lock.json
+
+# Push the new commit
+echo -e "\e[0;35mPushing the new commit\033[0m"
+git push --force-with-lease origin --no-verify "$current_branch"
+
+if [ $? == 1 ]; then
+  echo -e "\033[0;31mPushing changes (both bump version and released changed) has failed\033[0m"
+  exit 1
+fi
+
+echo -e "\e[0;35mFinished pushing the new commit\033[0m"
+
+echo -e "\033[92mChanges have been pushed\033[0m"
+echo -e "\033[1;33mPush bellow will fail and an error message will be displayed.\nBut \033[1mnot\033[1;33m be alarmed, look the output above to ensure that releases has been pushed\033[0m"
