TAWS-8 Avoid triggering github actions

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -102,7 +102,12 @@ fi
 echo -e "\e[0;35mFinished pushing the new commit\033[0m"
 
 sleep 3
-git pull origin "$current_branch"
+git pull --rebase origin "$current_branch"
+
+if [ $? -ne 0 ]; then
+  echo -e "\033[0;31mRebase failed. Please resolve conflicts and run the script again.\033[0m"
+  exit 1
+fi
 
 echo -e "\033[92mChanges have been pushed\033[0m"
 echo -e "\033[1;33mPush bellow will fail and an error message will be displayed.\nBut \033[1mnot\033[1;33m be alarmed, look the output above to ensure that releases has been pushed\033[0m"
